link_bashrc:
	ln -sf $(CURDIR)/.bashrc /home/$(USER)/.bashrc

open_webstorm_dir:
	xdg-open ~/.local/share/JetBrains/WebStorm*.3

edit_webstorm_icons:
	xdg-open ~/.local/share/JetBrains/WebStorm*.3/Atom*/lib/a-file-icon-idea-*.jar
