name: Issue workflow

on:
  issues:
    types: [opened, assigned, closed]

jobs:
  move_issue_after_opened:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        if: github.event.action == 'opened'
        with:
          project: Ofanotes
          column: To do
          repo-token: ${{ secrets.GH_TOKEN }}

  move_issue_after_assigned:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        if: github.event.action == 'assigned'
        with:
          project: Ofanotes
          column: In progress
          repo-token: ${{ secrets.GH_TOKEN }}

  move_issue_after_closed:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: Ofanotes
          column: Done
          repo-token: ${{ secrets.GH_TOKEN }}
