name: Continuous integration

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 14.15.1

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    # Check if commit message does not contain specified string.
    if: "!contains(github.event.head_commit.message , 'publish a new version')"
    steps:
      - name: Use "actions/checkout@master"
        uses: actions/checkout@master

      - name: Use "actions/setup-node@master" with Node version ${{ env.NODE_VERSION }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install lerna globally
        run: npm i -g lerna

      - name: Bootstrap project
        run: lerna bootstrap

      - name: Run eslint
        run: lerna run build --stream

      - name: Run eslint
        run: lerna run eslint-check --stream

      - name: Run tests
        run: lerna run test-ci --stream

      - name: Cache dependencies
        uses: actions/cache@master
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-npm-cache
